files: api
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: sort-simple-yaml
    -   id: check-toml
    -   id: check-merge-conflict
    -   id: check-yaml
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.212
    hooks:
    -   id: ruff
        args: ["--force-exclude"]
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
#-   repo: https://github.com/python-poetry/poetry
#    rev: 1.3.1
#    hooks:
#    -  id: poetry-check
#    -  id: poetry-lock
#-   repo: https://github.com/PyCQA/bandit
#    rev: 1.7.4
#    hooks:
#    -   id: bandit
